- date: '2025-06-24'
  id: url:https://hal.science/hal-05378598v1
  publisher: HAL Archive Ouverte
  title: Comparative study of characterization techniques in the Millimeter Waves
    and THz domains
- id: doi:10.23919/EuCAP63536.2025.10999502
- id: doi:10.1017/S1759078724001314
- date: '2024-11-11'
  id: url:https://imt-atlantique.hal.science/hal-04795549v1
  publisher: HAL Archive Ouverte
  title: High frequency modeling of a quasi-optical characterization bench
- id: doi:10.1109/AP-S/INC-USNC-URSI52054.2024.10686275
- id: doi:10.1109/AP-S/INC-USNC-URSI52054.2024.10687162
- id: doi:10.1109/AP-S/INC-USNC-URSI52054.2024.10686480
- date: '2024-06-04'
  id: url:https://imt-atlantique.hal.science/hal-04631622v1
  publisher: HAL Archive Ouverte
  title: "Mod\xE9lisation de syst\xE8mes quasi-optiques d\xE9di\xE9s \xE0 la caract\xE9\
    risation de mat\xE9riaux et \xE0 l'imagerie en bande J (220-330 GHz)"
- id: doi:10.23919/EuCAP60739.2024.10501609
- id: doi:10.1109/CAMA57522.2023.10352703
- id: doi:10.1109/CAMA57522.2023.10352886
- date: '2023-04-03'
  id: url:https://hal.science/hal-04164234v1
  publisher: HAL Archive Ouverte
  title: "Un banc de mesure de param\xE8tres S en espace libre sans moyennage ni filtrage\
    \ temporel : caract\xE9risation de mat\xE9riaux jusqu'\xE0 330 GHz"
- id: doi:10.23919/EuCAP57121.2023.10133635
- id: doi:10.1109/TAP.2023.3283043
- date: '2022-12-14'
  id: url:https://hal.science/hal-04169310v1
  publisher: HAL Archive Ouverte
  title: Fast Direct Solvers Based on the Quasi-Helmholtz Laplacian Filters
- id: doi:10.1109/ICEAA49419.2022.9899870
- id: doi:10.1109/AP-S/USNC-URSI47032.2022.9886398
- id: doi:10.1109/AP-S/USNC-URSI47032.2022.9886850
- date: '2022-06-08'
  id: url:https://cnrs.hal.science/hal-04342598v1
  publisher: HAL Archive Ouverte
  title: "Sources pr\xE9-d\xE9form\xE9es pour des analyses haute r\xE9solution de\
    \ l'impact du rayonnement radiofr\xE9quence sur l'activit\xE9 c\xE9r\xE9brale"
- id: doi:10.1109/TAP.2022.3161390
- date: '2021-06-28'
  id: url:https://hal.science/tel-04642819v1
  publisher: HAL Archive Ouverte
  title: Volume Integral Equation Methods for Forward and Inverse Bioelectromagnetic
    Problems
- id: doi:10.1109/IEEECONF35879.2020.9330486
- id: doi:10.3390/ijerph17072586
- id: doi:10.1109/CLEOE-EQEC.2019.8873045
- id: doi:10.1364/OE.27.021069
