- date: '2025-06-24'
  id: url:https://hal.science/hal-05378598v1
  publisher: HAL Archive Ouverte
  title: Comparative study of characterization techniques in the Millimeter Waves
    and THz domains
- id: doi:10.23919/EuCAP63536.2025.10999502
- id: doi:10.1017/S1759078724001314
- date: '2024-11-11'
  id: url:https://imt-atlantique.hal.science/hal-04795549v1
  publisher: HAL Archive Ouverte
  title: High frequency modeling of a quasi-optical characterization bench
- date: '2024-06-04'
  id: url:https://imt-atlantique.hal.science/hal-04631622v1
  publisher: HAL Archive Ouverte
  title: "Mod\xE9lisation de syst\xE8mes quasi-optiques d\xE9di\xE9s \xE0 la caract\xE9\
    risation de mat\xE9riaux et \xE0 l'imagerie en bande J (220-330 GHz)"
- id: doi:10.23919/EuCAP60739.2024.10501609
- date: '2023-04-03'
  id: url:https://hal.science/hal-04164234v1
  publisher: HAL Archive Ouverte
  title: "Un banc de mesure de param\xE8tres S en espace libre sans moyennage ni filtrage\
    \ temporel : caract\xE9risation de mat\xE9riaux jusqu'\xE0 330 GHz"
