- id: doi:10.1017/S1759078724001314 
  type: paper
  description: In this article, we present a simulation tool for modeling a quasi-optical bench for material characterization.
  date: 2025-02-11
  image: https://github.com/chenry02/material-sensing-simulation-lab/blob/main/images/20250211_paper1_simulationtool.png
  tags:
    - Gaussian beams
    - quasi-optical systems
    - material characterization

- id: doi:10.23919/EuCAP63536.2025.10999502
  image: https://github.com/chenry02/material-sensing-simulation-lab/blob/main/images/20250330_confpaper_eucap.png
  tags:
  - Gaussian beams
  - quasi-optical systems
  - skin permittivity
  - THz
